# Do not edit this file. It is managed by “skeleton”.
# For more informations: https://github.com/JosefFriedrich-shell/skeleton

test:
	@echo "PATH: $(PATH)"
	@echo
	@echo "PWD: $(shell pwd)"
	@echo

	./test/lib/test-runner.sh

readme:
	./test/lib/skeleton.sh --render-readme

sync_skeleton:
	mkdir -p test/lib
	wget -O test/lib/skeleton.sh https://raw.githubusercontent.com/JosefFriedrich-shell/skeleton.sh/master/skeleton.sh
	chmod a+x test/lib/skeleton.sh
	./test/lib/skeleton.sh --sync-skeleton

.PHONY: test sync_skeleton readme
